dependencies:
  - name: mysql
    version: ^0.2.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: mysql.enabled
  - name: redis
    version: 0.9.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: redis.enabled
