image: "presslabs/zinc:kub_compat"
imagePullPolicy: "Always"

config:
  debug: false
  secretKey: ""

  envName: "staging"
  brockerUrl: redis://zinc-redis:6370/0
  celeryResultBackend: redis://zinc-redis:6379/1
  lockServerUrl: redis://zinc-redis:6379/2

  dbName: "zinc"
  dbUser: "zinc"
  dbPassword: ""
  dbHost: zinc-mysql:3306
  dbEngine: django.db.backend.mysql

  socialAuthKey: ""
  socialAuthSecrete: ""

  latticeUser: ""
  latticePassword: ""

  awsKey: ""
  awsSecrete: ""

  sentryDSN: ""

  allowedHosts: [".stage.presslabs.net", ".presslabs.net"]


service:
  internalPort: 8000
  externalPort: 80

ingress:
  enabled: true
  hosts:
    - zinc2.stage.presslabs.net
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: true
