apiVersion: v1
kind: Secret
metadata:
  name: {{ template "redis.fullname" . }}
  labels:
    app: {{ template "redis.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  REDIS_PASSWORD: {{ .Values.redisPassword | default "" | b64enc | quote }}
  REDIS_CONNECT_URL: {{ include "redis.connect_url" . | b64enc | quote }}
  {{- if .Values.redisPassword }}
  redis.conf: {{ printf "requirepass %s\n\n%s" .Values.redisPassword .Values.redisConf | b64enc | quote }}
  {{- else }}
  redis.conf: {{ .Values.redisConf | b64enc | quote }}
  {{- end }}
