apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  - host: {{ required "Missing value .ingress.host" .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.service.externalPort }}
        path: /
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ template "name" . }}-tls
