apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    releases: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  SECRET: {{ required "Missing secret." .Values.config.secret | b64enc | quote }}
  CLIENT_ID: {{ required "Missing clientID." .Values.config.clientID | b64enc | quote }}
  CLIENT_SECRET: {{ required "Missing clientSecret." .Values.config.clientSecret | b64enc | quote }}
