{{- if .Values.minAvailable }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "stackdriver-zipkin.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "stackdriver-zipkin.name" . }}
      release: {{ .Release.Name | quote }}
  minAvailable: {{ .Values.minAvailable }}
{{- end }}
