apiVersion: v1
kind: Secret
metadata:
  name: {{ template "stackdriver-zipkin.fullname" . }}
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- range $key, $value := .Values.env }}
    {{ $key }}: {{ printf "%s" $value | b64enc | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secretFiles }}
    {{ $key }}: {{ printf "%s" $value | b64enc | quote }}
  {{- end }}
